# Docker Deployment configuration: https://gitlab.tandashi.de/GameBase/ci-configuration/blob/master/docker-deploy.yml
include:
  - project: 'GameBase/ci-configuration'
    file: 'docker-deploy.yml'

# Keep mode_modules between jobs (results in lower build times)
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    
stages:
  - verify
  - build
  - push
  - deploy

Verify branch:
  stage: verify
  image: trion/ng-cli-karma
  script:
    - npm run lint
    - ng test --code-coverage --progress false --watch false
  allow_failure: false
  artifacts:
    paths:
      - coverage/

Build release:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
      - dist/*
