# Docker Deployment configuration: https://gitlab.tandashi.de/GameBase/ci-configuration/blob/master/docker-deploy.yml
include:
  - project: 'GameBase/ci-configuration'
    file: 'docker-deploy.yml'

image: node:13-slim

# Keep mode_modules between jobs (results in lower build times)
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    
stages:
  - verify
  - build
  - push
  - deploy

before_script:
  - npm install

Verify branch:
  stage: verify
  script:
    - npm run lint
    - npm run test

Build Docker image:
  stage: build
  extends: Build image
  dependencies:
    - Verify branch

Build release:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
      - dist/*
