# Keep mode_modules between jobs (results in lower build times)
cache: &global_cache
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

stages:
  - install
  - verify
  - build
  - deploy

Install dependencies:
  stage: install
  script: npm i
  tags:
    - GameBase
    - docker
    - angular

Verify lint:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: verify
  image: trion/ng-cli-karma
  script: npm run lint
  tags:
    - GameBase
    - docker

Verify karma-test:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: verify
  image: trion/ng-cli-karma
  script: ng test --code-coverage --progress false --watch false
  artifacts:
    paths:
      - coverage/
  tags:
    - GameBase
    - docker

Verify E2E-test:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: verify
  image: trion/ng-cli-karma
  script: npm run e2e
  tags:
    - GameBase
    - docker

Build release:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: build
  script:
    - npm run build-live
  only:
    - master
  artifacts:
    paths:
      - dist/*
  tags:
    - GameBase
    - docker
    - angular

Build dev:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: build
  script:
    - npm run build-dev
  except:
    - master
  artifacts:
    paths:
      - dist/*
  tags:
    - GameBase
    - docker
    - angular

Deploy release:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - rm /opt/gamebase/frontend/live/*
    - cp dist/NG-Frontend/* /opt/gamebase/frontend/live/
  only:
    - master
  tags:
    - GameBase
    - shell

Deploy dev:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - rm /opt/gamebase/frontend/dev/*
    - cp dist/NG-Frontend/* /opt/gamebase/frontend/dev/
  except:
    - master
  tags:
    - GameBase
    - shell
