# Keep mode_modules between jobs (results in lower build times)
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - install
  - verify
  - build
  - deploy

Install dependencies:
  stage: install
  image: trion/ng-cli
  script: npm i

Verify lint:
  stage: verify
  image: trion/ng-cli-karma
  script: npm run lint

Verify karma-test:
  stage: verify
  image: trion/ng-cli-karma
  script: ng test --code-coverage --progress false --watch false
  artifacts:
    paths:
      - coverage/

Verify E2E-test:
  stage: verify
  image: trion/ng-cli-karma
  script: npm run e2e

Build release:
  stage: build
  image: trion/ng-cli
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
      - dist/*

Deploy releaase:
  stage: deploy
  script:
    - cp dist/NG-Frontend/* /opt/gamebase/frontend/live/
  only:
    - master
  tags:
    - GameBase
    - shell

Build dev:
  stage: build
  image: trion/ng-cli
  script:
    - npm run build
  except:
    - master
  artifacts:
    paths:
      - dist/*

Deploy dev:
  stage: deploy
  script:
    - cp dist/NG-Frontend/* /opt/gamebase/frontend/dev/
  except:
    - master
  tags:
    - GameBase
    - shell
