# Keep mode_modules between jobs (results in lower build times)
cache: &global_cache
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

stages:
  - install
  - generate-swagger-client
  - verify
  - build
  - deploy

Install dependencies:
  stage: install
  script: npm i
  tags:
    - GameBase
    - docker
    - angular

Generate swagger client:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: generate-swagger-client
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: npm run openapi
  artifacts:
    paths:
      - src/app/rest-client/
  tags:
    - GameBase
    - docker
    - angular

Verify lint:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: verify
  image: trion/ng-cli-karma
  script: npm run lint
  tags:
    - GameBase
    - docker

Verify karma-test:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: verify
  image: trion/ng-cli-karma
  script: ng test --code-coverage --progress false --watch false
  artifacts:
    paths:
      - coverage/
  tags:
    - GameBase
    - docker

Verify E2E-test:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: verify
  image: trion/ng-cli-e2e
  script: npm run e2e
  tags:
    - GameBase
    - docker

Build release:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: build
  script: npm run build-live
  only:
    - master
  artifacts:
    paths:
      - dist/*
  tags:
    - GameBase
    - docker
    - angular

Build dev:
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  stage: build
  script: npm run build-dev
  except:
    - master
  artifacts:
    paths:
      - dist/*
  tags:
    - GameBase
    - docker
    - angular

Deploy release:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - rm /opt/gamebase/frontend/live/*
    - cp dist/GameBase-Frontend/* /opt/gamebase/frontend/live/
  only:
    - master
  tags:
    - GameBase
    - shell

Deploy dev:
  stage: deploy
  cache: {}  # no cache required for deployment
  script:
    - rm /opt/gamebase/frontend/dev/*
    - cp dist/GameBase-Frontend/* /opt/gamebase/frontend/dev/
  except:
    - master
  tags:
    - GameBase
    - shell

pages:
  stage: deploy
  cache:
    # inherit all global cache settings
    <<: *global_cache
    key: pages
    paths:
      - public
    policy: pull-push
  dependencies:
    - Verify karma-test
  script:
    - mv coverage/Frontend/* coverage/
    - mkdir -p public/
    - cp -a coverage/* public/
  only:
    - master
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
  tags:
    - GameBase
    - docker

pages:
  stage: deploy
  cache:
    # inherit all global cache settings
    <<: *global_cache
    key: pages
    paths:
      - public
    policy: pull-push
  dependencies:
    - Verify karma-test
  script:
    - mv coverage/GameBase-Frontend/* coverage/
    - mkdir -p public/dev/
    - cp -a coverage/* public/dev/
  except:
    - master
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
  tags:
    - GameBase
    - docker
