# Keep mode_modules between jobs (results in lower build times)
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - verify
  - build
  - deploy

Verify branch:
  stage: verify
  image: trion/ng-cli-karma
  script:
    - npm install
    - npm run lint
    - ng test --code-coverage --progress false --watch false
  allow_failure: false
  artifacts:
    paths:
      - coverage/

Build release:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
      - dist/*

Deploy releaase:
  stage: deploy
  script:
    - ls
  only:
    - master
  tags:
    - GameBase
    - shell

Build dev:
  stage: build
  script:
    - npm run build
  except:
    - master
  artifacts:
    paths:
      - dist/*

Deploy dev:
  stage: deploy
  script:
    - ls
  except:
    - master
  tags:
    - GameBase
    - shell
