# Keep mode_modules between jobs (results in lower build times)
cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - verify
  - build
  - deploy

Install dependencies:
  stage: install
  image: trion/ng-cli
  script: npm i
  tags:
    - GameBase
    - docker

Verify lint:
  stage: verify
  image: trion/ng-cli
  script: npm run lint
  tags:
    - GameBase
    - docker

Verify karma-test:
  stage: verify
  image: trion/ng-cli-karma
  script: ng test --code-coverage --progress false --watch false
  artifacts:
    paths:
      - coverage/
  tags:
    - GameBase
    - docker

Verify E2E-test:
  stage: verify
  image: trion/ng-cli-karma
  script: npm run e2e
  tags:
    - GameBase
    - docker

Build release:
  stage: build
  script:
    - npm run build
  only:
    - master
  artifacts:
    paths:
      - dist/*
  tags:
    - GameBase
    - docker
    - angular

Deploy releaase:
  stage: deploy
  script:
    - cp dist/NG-Frontend/* /opt/gamebase/frontend/live/
  only:
    - master
  tags:
    - GameBase
    - shell

Build dev:
  stage: build
  script:
    - npm run build
  except:
    - master
  artifacts:
    paths:
      - dist/*
  tags:
    - GameBase
    - docker
    - angular

Deploy dev:
  stage: deploy
  script:
    - cp dist/NG-Frontend/* /opt/gamebase/frontend/dev/
  except:
    - master
  tags:
    - GameBase
    - shell
